version: "3.5"
services:
  mongo:
    image: "mongo"
    container_name: bank-mongo-container
    ports:
      - "27020:27017"
    volumes:
      - ./mongoData:/data/db

  flask:
    image: bank-flask:1.0
    container_name: bank-api-container
    depends_on:
      - mongo
    command: python src/run.py
    ports:
      - "5001:5001"
    environment:
      FLASK_ENV: "development"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
